### ISSUE TITLE
Autologin Issue

### ISSUE THREAD

**Issue by Bra1nsen** [Paraphraser/PiBuilder#7]
![image](https://user-images.githubusercontent.com/58213050/231810484-59b4e95f-9ba1-4d62-9c6a-82e8f9375b2f.png)

I use ssh and remote desktop for communicating with my raspberry pi all sky imager.

Its not possible to set autologin for Consol AND Desktop.

Recently I had to add a new super user to connect again via remote desktop because the account is stucked.

[Related ](https://stackoverflow.com/questions/70146297/raspberry-pi-remote-desktop-connection-problem-giving-up)

Can you help?

**Comment by Paraphraser** [comment]
Further to what I wrote before, after a bit more Googling (and noticing a lot of people complaining about having trouble getting the VNC service built into the Pi to actually work properly), I stumbled across [this tutorial](https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-vnc-on-debian-11).

### on the Pi

I began by going back into raspi-config, disabling VNC, setting the boot mode back to B1, and rebooting.

Then I followed the tutorial:

```
$ sudo apt update
$ sudo apt install -y xfce4 xfce4-goodies
$ sudo apt install -y tightvncserver
$ sudo apt install -y dbus-x11
```

The first one installed a *lot* of stuff. I'm never particularly happy when something has crate-loads of dependencies but I was doing this on a test server so it didn't really matter. The tutorial continues:

```
$ vncserver
```

where you set a password to control access to VNC (not the user account on the Pi).

```
$ vncserver -kill :1
$ mv ~/.vnc/xstartup ~/.vnc/xstartup.bak
$ echo -e '#!/usr/bin/env bash\nxrdb $HOME/.Xresources\nstartxfce4 &\n' >~/.vnc/xstartup
$ chmod +x ~/.vnc/xstartup
$ vncserver
```

### on the Mac/Linux box

Then, on the machine you want to connect **from** (this isn't immediately clear in the tutorial):

```
$ ssh -L «localPort»:127.0.0.1:«remotePort» -C -N «user»@«host»
```

where:

* `«localPort»` can be anything but is usually 5901
* `«remotePort»` should be 5901 (unless you change the config)
* `«user»` would be the login name of the account on the Pi where you were running `vncserver` above
* `«host»` would be the IP address or hostname or fully-qualified domain name of the Pi:

Example:

```
$ ssh -L 5901:127.0.0.1:5901 -C -N pi@192.168.1.100
```

In words, `-L` listen on local port 5901 and securely forward to remote port 5901 on 192.168.1.100, connecting as the user "pi". `-C` enables compression and `-N` doesn't execute any commands (ie doesn't try to start bash).

Now, in my case, I have SSH certificates set up so I can just abbreviate that to:

```
$ ssh -L 5901:127.0.0.1:5901 -C -N sec-dev
```

where "sec-dev" is the hostname of the Pi. No password prompt or anything else. Just straight in. The `pi@` is implied from the hostname and comes from my `~/.ssh/config` file.

If you haven't set up either certificates or arranged key-exchange for passwordless login, you'll probably face the TOFU (trust on first use) challenge and a password challenge.

The command will then freeze.

Then, while that command is running, start your VNC client and connect to 127.0.0.1:5901 (or localhost:5901). It wanted the password set the first time I ran `vncserver` as above. Worked first time from the macOS "connect to server" command, no drama at all:

<img width="1136" alt="Screen Shot 2023-04-14 at 16 17 32" src="https://user-images.githubusercontent.com/34226495/231962493-67736b0a-96ce-4570-9199-baf4a2033734.png">

To exit, you quit the screen sharing window, and then <kbd>CONTROL</kbd>+<kbd>C</kbd> the SSH command.

As an alternative, you can run the SSH command in the background:

```
$ ssh -L 5901:127.0.0.1:5901 -C -N sec-dev &
```

When you're done, kill it with:

```
$ kill %1
```

### but if it's Windows…

I don't know. The tutorial burbles on about putty which I have never used and don't understand but I guess it would make sense to a Windows user.

### doing without SSH

Using SSH gives you secure transport. If you want to do without, you can just go straight to:

```
vnc://host-or-IP:5901/
```

That worked just fine from both macOS and a VNC app on my iPad.

Personally, I don't care about the SSH encryption for VNC traffic because:

1. If I'm working locally, it's just my local home network; and
2. If I'm working remotely, everything is already encrypted via ZeroTier or WireGuard.

### other odds and ends

The Pi did not hang when I rebooted while VNC was running. That's only N=1 so not much of a test but it's promising.

After the reboot, VNC is not available until you (a) connect to the Pi and (b) run `vncserver`. If you wanted it to be always-on, you'd probably need something like an `@reboot` entry in your crontab.

**Comment by Bra1nsen** [comment]
Hi Paraphraser, 

I was not expecting such a detailed analysis, your expertise isincredibly helpful. 

First of all, I just use xrdp for a remote desktop session (Windows 10). Your suggestion for connection a monitor for resolving the issue wont be a longterm solution, since the problem could occur again and again. 

![image](https://user-images.githubusercontent.com/58213050/231981227-3383379b-d1dc-4dfc-a191-522d3ac73ccc.png)

On the left side, I logged in with my "pi" user, its connected but no screening, since I believe its stucked in a login phase or something like this. After creating via ssh a new super user "dlr", it works for now..,but I guess the same can happen here again. Iam looking for a solution to get the "pi" user back at my remote desktop screen.. I will try a bit around with autologgin options and report if something worked...

**Comment by Paraphraser** [comment]
Some questions just become voyages of discovery. I get as much out of the research as I hope you do when I show what I have done.

Is "pi" still "stuck"? The most common reasons are something wrong with either `.profile` or `.bashrc`. If you can login as root then just go to `/home/pi` and rename those two files so they don't run at login time. Another possibility is a misbehaving cron job. That's stored at `/var/spool/cron/crontabs/pi` and can be moved out of the way too.

**Comment by Bra1nsen** [comment]
hey Paraphraser Iam still trying to resolve this issue: 
![image](https://user-images.githubusercontent.com/58213050/232419452-b7ca2ee7-1dfd-4d76-94c3-bdcaf4180842.png)

I renamed  .profile and .bashrc and rebootet, still not able to get a screen working with remote desktop using "pi" as user.

**Comment by Bra1nsen** [comment]
The issue seems to be related to "video" and "render" groups..

https://forums.raspberrypi.com/viewtopic.php?t=323471&hilit=xrdp&sid=4b40dd5ac0f90de62c6055be41c841af&start=25 thanks for your help Paraphraser, I will go with the 2nd user I created.

**Comment by Bra1nsen** [comment]
if you create a new user and add it to the group video and render:

sudo usermod -a -G plugdev,adm,dialout,cdrom,sudo,audio,video,render,games,input,netdev,spi,i2c,gpio <new_username>

the same issue occur

**Comment by Paraphraser** [comment]
Well, I've left the TightVNC installation running on my test machine and, so far, it has not misbehaved at all. I'm thinking of rewriting the VNC tutorial say something along the lines of "option 1 is to enabled the built-in option while option 2 is TightVNC. A lot of people report problems getting the built-in version working reliably so option 2 is recommended at this point".
