### ISSUE TITLE
menu.sh fails when nodered is selected.

### ISSUE THREAD

**Issue by oderflallc** [Paraphraser/PiBuilder#8]
menu.sh fails when building nodered:

Starting NodeRed Build script
Error running PreBuildHook on 'nodered'
Traceback (most recent call last):
  File "./scripts/buildstack_menu.py", line 460, in runPrebuildHook
    exec(code, execGlobals, execLocals)
  File "./.templates//nodered/build.py", line 396, in <module>
    main()
  File "./.templates//nodered/build.py", line 386, in main
    eval(toRun)()
  File "./.templates//nodered/build.py", line 119, in preBuild
    installCommand = addonsSelected["dockerFileInstallCommand"]
                     ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable

Thanks a million

**Comment by Noschvie** [comment]
This seems to be the wrong project, better you ask IOTstack.

**Comment by Paraphraser** [comment]
@oderflallc - @Noschvie is correct that this is an IOTstack problem, not a PiBuilder problem but, rather than wait for you to open an issue on IOTstack, I will try to help you here.

I have not been able to replicate your problem *exactly* but I can get close if I do this:

1. `./menu.sh`
2. Choose "Build Stack"
3. Use the up/down arrow keys to put the cursor on "nodered"
4. Press <kbd>space</kbd> to select "nodered".
5. Press <kbd>Enter</kbd> to build the stack.

Those five steps get me this error:

<img width="840" alt="Screenshot 2023-11-19 at 08 27 48" src="https://github.com/Paraphraser/PiBuilder/assets/34226495/2153d1f7-26e4-4b9c-92e2-4ac7757d8192">

That error is a fairly common problem with people new to IOTstack. Adding Node-RED into your stack needs some extra steps:

1. `./menu.sh`
2. Choose "Build Stack"
3. Use the up/down arrow keys to put the cursor on "nodered"
4. Press <kbd>space</kbd> to select "nodered".
5. Without moving the cursor, press right arrow.
6. Choose "Select & build addons list".
7. Use the up/down arrow keys and <kbd>space</kbd> key to choose your add-on nodes.

	> If you don't know which ones you need, it's OK to just leave the list with the defaults selected.

8. When the list of add-on nodes is how you want it, press <kbd>Enter</kbd> to save that list.
9. Choose "Go back".
10. Press <kbd>Enter</kbd> to build the stack.

Although the menu does prompt you at step 5, I don't the message is particularly clear:

```
odered (fileIssues) - ['/addons_list.yml does not exist. Build addons file in options to fix. This is optional']
```

What that *means* is "press the right-arrow". Why it doesn't simply say that is a mystery. The message is also misleading because it isn't actually optional. It's mandatory (for Node-RED).

My guess is that if you go back into the menu, then "Build Stack", then put the cursor on "nodered", and pick up from step 5 by pressing the right arrow, you will be able to fix the problem.

If you can't then the simplest approach is to fool the menu into thinking it's a brand new build:

```
$ cd ~/IOTstack
$ rm -rf docker-compose.yml services
$ ./menu.sh
```

<hr>

Earlier I said "I have not been able to replicate your exact problem". If you compare/contrast your traceback with mine, you will see they are similar for code lines 460, 396 and 386 but differ at the point of the base call. Your error traces back to line 119 while mine traces back to line 114.

The relevant area of code is:

<img width="765" alt="Screenshot 2023-11-19 at 08 34 32" src="https://github.com/Paraphraser/PiBuilder/assets/34226495/f92169ce-63bb-43d8-85ae-847db2ef29fa">

You can see from line 109 that this area of code is all to do with building Node-RED. Given the sequence of events I described above where I do **not** press the right-arrow to select the add-ons, I can easily explain why line 114 leads to a crash:

* the expected `addons_list.yml` file has not been created.

Conversely, I can't explain how, under normal conditions, I can get past line 114 and fail at line 119. The only way I can contrive that is by taking action outside the menu. Something like this:

```
$ cd ~/IOTstack
$ mkdir -p services/nodered
$ touch ./services/nodered/addons_list.yml
$ ./menu.sh
```

If I do that then select "nodered" and build the stack I get:

<img width="618" alt="Screenshot 2023-11-19 at 09 09 08" src="https://github.com/Paraphraser/PiBuilder/assets/34226495/ca135db4-95cb-4c27-9822-ad9a1603e794">

That's identical to your crash.

If you did something "outside the menu" similar to what I just did then maybe try the `rm` command (above) to persuade the menu to start over properly.

If that doesn't help and you think you might've accidentally done more damage to the IOTstack folder structure, the simplest solution is to start over with a clean clone:

```
$ cd
$ sudo rm -rf IOTstack
$ git clone https://github.com/SensorsIot/IOTstack.git
$ cd IOTstack
$ ./menu.sh
```

Hope this helps.
