### ISSUE TITLE
 ZIGBEE2MQTT_DEVICE_PAT

### ISSUE THREAD

**Issue by dherakles** [Paraphraser/PiBuilder#9]
Danke, ich bin begeistert von dieser Repository, die Neuinstallation auf einem Raspi 5 mit Image 24-11-19 hat fehlerfrei funktioniert. Nach Bildung des Stacks, der erfreulich viele Möglichkeiten bietet, einzig Watchtower fehlt mir, folgte nach docker-compose up -d:

error while interpolating services.zigbee2mqtt.devices.[]: required variable ZIGBEE2MQTT_DEVICE_PATH is missing a value: eg echo ZIGBEE2MQTT_DEVICE_PATH=/dev/ttyACM0 >>~/IOTstack/.env

mfG
dherakles

**Comment by Paraphraser** [comment]
My apologies for not being able to answer you in your own language.

WatchTower was discussed at one point but the community took the view that automating image updates was not a good idea. Automatic updates lead to surprises and surprises are usually not a good idea with Information Technology. It is better to do manual "pulls". By not supporting WatchTower, IOTstack is trying to (gently) guide people away from using it.

There is, however, absolutely nothing stopping you from adding **any** service definition to your `docker-compose.yml`. It doesn't have to be officially supported by IOTstack. For example, I run DHCPD and BIND9 containers. You won't find those in IOTstack.

PiBuilder gives you a solid platform. IOTstack gives you a good way to get **started** with docker-compose. The advice I give people all the time is to study what the menu has done until you understand it, then stop using the menu and just use a text editor. The reason is that the menu is really only good at generating your first `docker-compose.yml`. It is (relatively) terrible at long-term maintenance.

It's really easy to add containers. Here's an example adding WordPress:

```
$ cd ~/IOTstack
$ sed -e "s/^/  /" ./.templates/wordpress/service.yml >>docker-compose.yml
```

That's it. The reason for the `sed` command is it adds two spaces to the start of each line, so that everything lines-up properly in the `docker-compose.yml` file.

<hr>

```
error while interpolating services.zigbee2mqtt.devices.[]: required variable ZIGBEE2MQTT_DEVICE_PATH is missing a value:
eg echo ZIGBEE2MQTT_DEVICE_PATH=/dev/ttyACM0 >>~/IOTstack/.env
```

Containers can't see which devices have been connected to the host. You have to work that out for yourself and then provide the information to the container.

The steps are explained in the [IOTstack Zigbee2MQTT documentation](https://sensorsiot.github.io/IOTstack/Containers/Zigbee2MQTT/).

I hope this helps.

**Comment by dherakles** [comment]
Hi, lieben Dank für die prompte Antwort. Ich bin glücklich Ihr Repository gefunden zu haben und wunschlos glücklich. Als Neuling bei Raspi muss ich noch etliches lernen und meine Erfahrung machen. Dabei hilft mir auch Ihre perfekt ausgearbeitete Anleitung, Respekt das war viel Arbeit und noch mehr Hirn! Den  Watchtower werde ich auf Grund gleicher Bedenken nicht verwenden, danke für den Hinweis. Wenn ich mein System zum Laufen gebracht habe freue ich mich darauf weitere Container hinzuzufügen. Zunächst studiere ich den Link zu Zigbee.
mit herzlichen Grüssen,
dherakles
